#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case "$1" in
prereqs)
    prereqs
    exit 0
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line
copy_exec /sbin/dmsetup /sbin
copy_exec /sbin/blockdev /sbin
manual_add_modules dm_mod dm-ddi
